# M.Usman Akram
## Numpy

-  NumPy is a Python library.

-  NumPy is used for working with arrays.

-  NumPy is short for "Numerical Python".
-  Numpy is a base of Data science.

In [1]:
import numpy as np
array_3=np.array(23)
print(array_3)

23


In [2]:
import numpy as np
a=np.array(15)
print(a)

15


#### 1-D Arrays:
- An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

- These are the most common and basic arrays.

#### Example : 

In [3]:
import numpy as np
array_4=np.array([1,2,3,4,5])
print(array_4)

[1 2 3 4 5]


In [4]:
import numpy as np
b=np.array([12,45,67])
print(b)

[12 45 67]


#### 2- D Array:
- An array that has 1-D arrays as its elements is called a 2-D array.

- These are often used to represent matrix or 2nd order tensors.

#### Example: 


In [5]:
import numpy as np
array_5= np.array(([1,2,3,4],[4,3,2,1]))
print(array_5)

[[1 2 3 4]
 [4 3 2 1]]


In [6]:
import numpy as np
c= np.array(([23,56,57],[12,65,90]))
print(c)

[[23 56 57]
 [12 65 90]]


#### 3 D Array:
- An array that has 2-D arrays (matrices) as its elements is called 3-D array.

- These are often used to represent a 3rd order tensor.

#### Example:

In [7]:
import numpy as np
array_6=np.array(([[1,2,3],[1,2,3]],[[3,4,5],[7,54,32]]))
print(array_6)

[[[ 1  2  3]
  [ 1  2  3]]

 [[ 3  4  5]
  [ 7 54 32]]]


#### Number of Dimensions:
-  NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

#### Example : 

In [8]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d.ndim)


3


#### Higher Dimensional Arrays:
- An array can have any number of dimensions.

- When the array is created, you can define the number of dimensions by using the ndmin argument.

#### Example: 

In [9]:
import numpy as np
array_7=np.array([[1,2,3],[1,2,3]],ndmin=5)
print(array_7)
print("The dimension of Array_7 is : ", array_7.ndim)

[[[[[1 2 3]
    [1 2 3]]]]]
The dimension of Array_7 is :  5


#### Example # 02:

In [10]:
import numpy as np
array_8=np.array([[1,2,3],[3,2,1]],ndmin=8)
print(array_8)
print("Mr.Usman The dimension of Array_8 is :",array_8.ndim)


[[[[[[[[1 2 3]
       [3 2 1]]]]]]]]
Mr.Usman The dimension of Array_8 is : 8


### NumPy Array Indexing:
- Array indexing is the same as accessing an array element.

- You can access an array element by referring to its index number.

- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

### Access 1-D Arrays:
- we can get the elements of 1-D array by using the index number.

#### Example:
- Creat 1D array and access its third element.

In [11]:

import numpy as np
array_9=np.array([1,2,3,4,5,6,7,8,9])
print("Mr.Usman The Third element of array is : ",array_9[2])

Mr.Usman The Third element of array is :  3


#### Example # 02:
- Get third and fourth elements from the  array and add them.

In [12]:

import numpy as np
array_1=np.array([1,2,3,4,5,6,7,8])
print(array_1[2]+array_1[3])

7


In [13]:
import numpy as np
z=np.array([12,45,67,97,43])
print(z[3])

97


### Access 2-D Arrays:
- To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

- Think of 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column.

#### Example:
- Access the element on the second row, 1 column.

In [14]:

import numpy as np
array_2=np.array(([1,2,3],[23,56,78]))   
print(array_2[1,0])

23


#### Example # 02:  
- Access the element on the 2nd row, 5th column.

In [15]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


### Access 3-D Arrays:
- To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

#### Example:
 - Access the third element of the second array of the first array.

In [16]:

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


### NumPy Array Slicing:

- Slicing in numpy means taking elements from one given index to another given index.

- We pass slice instead of index like this:              start : end.

- We can also define the step, like this:              start:end:step.

- If we don't pass start its considered 0

- If we don't pass end its considered length of array in that dimension

-  If we don't pass step its considered 1

#### Example: 
- Slice elements from index 1 to index 5 from the  array.

In [17]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


#### Example # 02:
- Slice elements from index 4 to the end of the array.

In [18]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:6])

[1 2 3 4 5 6]


### Negative Slicing:
- Use the minus operator to refer to an index from the end.

#### Example:
- Slice from the index 3 from the end to index 1 from the end.

In [19]:
import numpy as np

arr = np.array([1, 2,3,4,5,6,7])

print(arr[-3:-1])

[5 6]


- Use the step value to determine the step of the slicing.

In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0:6:2])

[1 3 5]


### Slicing 2-D Arrays:

#### Example:
- From the second element, slice elements from index 1 to index 4 (not included):

In [21]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1:4])

[2 3 4]


In [22]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


### Data Types in Python
-  By default Python have these data types:

   - strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
   - integer - used to represent integer numbers. e.g. -1, -2, -3
   - float - used to represent real numbers. e.g. 1.2, 42.42
   - boolean - used to represent True or False.
   -  complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j


### Data Types in NumPy
- NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

   - Below is a list of all data types in NumPy and the characters used to represent them.

            i - integer
            b - boolean
            u - unsigned integer
            f - float
            c - complex float
            m - timedelta
            M - datetime
            O - object
            S - string
            U - unicode string
            V - fixed chunk of memory for other type ( void )


#### Checking the Data Type of an Array:
- The NumPy array object has a property called "dtype"that returns the data type of the array.


#### Example:
- Get the data type of an array object.


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


 ####  Example
- Get the data type of an array containing strings.

In [24]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


### Converting Data Type on Existing Arrays
- The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

- The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

- The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly     like float for float and int for integer.

#### Example:
- Change data type from float to integer by using 'i' as parameter value.

In [1]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [3]:
import numpy as np
a=np.array([1.2,45.6,23.6])
b=a.astype("i")
print(a)
print(a.dtype)
print(b)
print(b.dtype)

[ 1.2 45.6 23.6]
float64
[ 1 45 23]
int32


In [68]:
import numpy as np 
a=np.array([12.3,3.9,78.9])
b=a.astype('i')
print(b)
print(b.dtype)
print(a.dtype)

[12  3 78]
int32
float64


#### Example # 02:
- Change data type from float to integer by using int as parameter value:

In [4]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print("Mr.Usman Data type is :",newarr.dtype)

[1 2 3]
Mr.Usman Data type is : int32


In [5]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype("i")

print(newarr)
print("Mr.Usman Data type is :",newarr.dtype)

[1 2 3]
Mr.Usman Data type is : int32


#### Example # 03:
- Change data type from integer to boolean:


In [27]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print("Mr.Usman Data type is :",newarr.dtype)

[ True False  True]
Mr.Usman Data type is : bool


#### Example # 04:
- change data tye from float to integer.

In [28]:
import numpy as np
array_4=np.array([1.2,3.4])
array_5=array_4.astype(int)
print(array_4.dtype)
print(array_5.dtype)

float64
int32


### NumPy Array Copy vs View:
- The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

- The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

- The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.
- The copy SHOULD NOT be affected by the changes made to the original array.


#### COPY:

#### Example:
- Make a copy, change the original array, and display both arrays:

In [3]:
import numpy as np
array_6=np.array([1,2,3,4,5])
array_7=array_6.copy()
print(array_6)
array_7[0:1]=4
print(array_7)


[1 2 3 4 5]
[4 2 3 4 5]


#### VIEW: 

#### Example:
- Make a view, change the original array, and display both arrays:

In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


### Check if Array Owns its Data:
- As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

- Every NumPy array has the attribute base that returns None if the array owns the data.

- Otherwise, the base  attribute refers to the original object.

#### Example:
              -Print the value of the base attribute to check if an array owns it's data or not.

In [31]:
import numpy as np
array_8=np.array([12,34,56,76,3])
a=array_8.copy()
b=array_8.view()
print(a.base)
print(b.base)


None
[12 34 56 76  3]


#### Example # 02:
- The copy returns None.
- The view returns the original array.


In [32]:
import numpy as np
array_1=np.array([21,45,43,23])
x=array_1.copy()
y=array_1.view()
print(x.base)
print(y.base)

None
[21 45 43 23]


### NumPy Array Shape:
- The shape of an array is the number of elements in each dimension.

### Get the Shape of an Array:
- NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

### Example :
- Print the shape of a 2-D array.

In [33]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


#### Example # 02:
- Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4.

In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


### NumPy Array Reshaping : 
- Reshaping means changing the shape of an array.

- The shape of an array is the number of elements in each dimension.

- By reshaping we can add or remove dimensions or change number of elements in each dimension.

### Reshape From 1-D to 2-D:
 #### Example :
- Convert the  1-D array with 12 elements into a 2-D array.

- The outermost dimension will have 4 arrays, each with 3 elements.

In [35]:
import numpy as np
array_1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array_2=array_1.reshape(4,3)
print(array_1)
print(array_2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Reshape From 1-D to 3-D:

#### Example:

In [36]:
import numpy as np
array_1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
array_2=array_1.reshape(2,2,3)
print(array_1)
print(array_2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Unknown Dimension:
- You are allowed to have one "unknown" dimension.

- Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

- Pass -1 as the value, and NumPy will calculate this number for you.
- We can not pass -1 to more than one dimension.

#### Example:
- Convert 1D array with 8 elements to 3D array with 2x2 elements.

In [37]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7,12])
newarr = arr.reshape(2, 2,-1)
print(newarr)



[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7 12]]]


### Flattening the arrays:
- Flattening array means converting a multidimensional array into a 1D array.

- We can use reshape  (-1)  to do this.

#### Example:
- Convert the array into a 1D array.

In [38]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


### NumPy Array Iterating :
- Iterating means going through elements one by one.

- As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

- If we iterate on a 1-D array it will go through each element one by one.

#### Example:
- Iterate on the elements of the following 1-D array.

In [39]:
import numpy as np

arr = np.array([1, 2, 3,4,5])

for x in arr:
  print(x)

1
2
3
4
5


### Iterating 2-D Arrays:
- In a 2-D array it will go through all the rows.

#### Example:
- Iterate on the elements of the following 2-D array.

In [40]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


#### Example # 02:
- Iterate on each scalar element of the 2-D array.

In [41]:
import numpy as np
array_1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in array_1:
    for y in x:
        print(y)
  
    

1
2
3
4
5
6
7
8
9
10


In [42]:
import numpy as np
array_1=np.array([[[1,2,3],[4,5,6]],[[12,34,56],[344,7,1]]])
for x in np.nditer(array_1):
    print(x)

1
2
3
4
5
6
12
34
56
344
7
1


### Iterating With Different Step Size:


#### Example :
- Iterate through every scalar element of the 2D array skipping 1 element.

In [43]:
import numpy as np
array_4=np.array([[1,2,3,4,5],[6,7,8,9,10]])
for x in np.nditer(array_4[ : , ::2]):
    print(x)

1
3
5
6
8
10


### Enumerated Iteration Using ndenumerate():
- Enumeration means mentioning sequence number of somethings one by one.

- Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

### 1D Array:

In [44]:
import numpy as np
arr =np.array([1,2,3,4,5])
for x,y in np.ndenumerate(arr):
    print(x,y)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


### 2D Array:

In [45]:
import numpy as np
array_5=np.array([[1,2,3],[4,5,6]])
print(array_5)
for y,x in np.ndenumerate(array_5):
 print(y,x)

[[1 2 3]
 [4 5 6]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


##  NumPy Joining Array:

### Joining NumPy Arrays:
- Joining means putting contents of two or more arrays in a single array.
- We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

#### Example :
- 1 D Array


In [46]:
import numpy as np
array_1=np.array([12,45,32,21,23])
array_2=np.array([1,2,3,4,5])
array_3=np.concatenate ((array_1,array_2))
print(array_3)

[12 45 32 21 23  1  2  3  4  5]


#### Example # 02 :
- 2 D Array


In [47]:
import numpy as np
array_5=np.array([[1,2,3,4],[5,6,7,8]])
array_6=np.array([[2,3,4,5],[5,6,7,8]])
array_3=np.concatenate((array_5,array_6))
print(array_3)

[[1 2 3 4]
 [5 6 7 8]
 [2 3 4 5]
 [5 6 7 8]]


#### Example # 03:
-  if we pass axis = 1 when arrays will join row wise.

In [48]:
import numpy as np
array_1=np.array([[1,2,3,4],[5,6,7,8]])
array_2=np.array([[1,2,3,4],[5,6,7,8]])
array_3=np.concatenate((array_1,array_2),axis=1)
print(array_3)

[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


### Splitting NumPy Arrays
- Splitting is reverse operation of Joining.

- Joining merges multiple arrays into one and Splitting breaks one array into multiple.

- We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

### Example:
- Split the array in 3 parts:

In [49]:
import numpy as np
array_1=np.array([1,2,3,4,5,6,7,8,9])
newarray=np.array_split(array_1,4)
print(newarray)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


### Split Into Arrays:
- The return value of the array_split() method is an array containing each of the split as an array.

- If you split an array into 3 arrays, you can access them from the result just like any array element.

#### Example:

In [50]:
import numpy as np
array_5=np.array([1,2,3,4,5,6,7,8,9])
array_6=np.array_split(array_5,3)
print(array_6[0])
print(array_6[1])
print(array_6[2])

[1 2 3]
[4 5 6]
[7 8 9]


### Split 2D Array:

#### Example :

In [51]:
import numpy as np
array_7=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
array_8=np.array_split(array_7,3)
print(array_8)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18]])]


#### Example # 02:

In [52]:
import numpy as np
array_7=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
array_8=np.array_split(array_7,3)
print(array_8[0])
print(array_8[1])
print(array_8[2])


[[1 2 3 4 5 6]]
[[ 7  8  9 10 11 12]]
[[13 14 15 16 17 18]]


### Example # 03 :
- Split the 2-D array into three 2-D arrays along rows.

In [53]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr,3,axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


- An alternate solution is using hsplit() opposite of hstack()

#### Example # 04 :

In [54]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## NumPy Searching Arrays:

### Searching Arrays:
- You can search an array for a certain value, and return the indexes that get a match.

- To search an array, use the where() method.


#### Example:
        -find the index of element 4.

In [55]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8])
x=np.where(array==4)
print(x)

(array([3], dtype=int64),)


#### Example # 02:
          - find a number in 2 D array.

In [56]:
import numpy as np
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array)
y=np.where(array == 3)
print(" Mr.Usman Malik The index of 8 is : ",y)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 Mr.Usman Malik The index of 8 is :  (array([0], dtype=int64), array([2], dtype=int64))


#### Example # 03:
                  - find all indexes where the numbers are even and odd.

In [57]:
import numpy as np
array=np.array([21,45,76,22,54,32,11,3,4,33,2,34,4324,3,324,23])
x=np.where(array%2==0)
y=np.where(array%2==1)
print("MR .Usman the indexes of even numbers are :", x)
print("MR .Usman the indexes of odd numbers are :", y)

MR .Usman the indexes of even numbers are : (array([ 2,  3,  4,  5,  8, 10, 11, 12, 14], dtype=int64),)
MR .Usman the indexes of odd numbers are : (array([ 0,  1,  6,  7,  9, 13, 15], dtype=int64),)


### Search Sorted:
- There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

- The searchsorted() method is assumed to be used on sorted arrays.

#### Example :

In [58]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 9)

print(x)

3


#### Example # 02:

In [59]:
import numpy as np
array=np.array([1,21,34,53,22,45])
x=np.where(array==21)
a=np.searchsorted(array,34)
print(x)
print(a)
print(b)

(array([1], dtype=int64),)
2
[12 34 56 76  3]


### Search From the Right Side:
- By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [60]:
import numpy as np
array=np.array([1,2,3,4,5,6,7,8])
t=np.searchsorted(array,4,side='right')
print(t)


4


#### Example 
- seach multiple values .

In [61]:
import numpy as np

arr = np.array([1, 3, 5, 7,34,2,21,12,324,34234,])

x = np.searchsorted(arr, [2, 34,21])

print(x)

[1 8 4]


## Sorting Arrays:
- Sorting means putting elements in an ordered sequence.

- Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

- The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [62]:
import numpy as np
array_1=np.array([21,323,1,33,26,77,34])
x=np.sort(array_1)
print(x)

[  1  21  26  33  34  77 323]


- You can also sort arrays of strings, or any other data type.

#### Example:

In [63]:
import numpy as np
array=np.array(["Usman","Ahtsham","zain","Hadir"])
x=np.sort(array)
print(x)

['Ahtsham' 'Hadir' 'Usman' 'zain']


### Sorting a 2-D Array:
- If you use the sort() method on a 2-D array, both arrays will be sorted.
#### Example:

In [64]:
import numpy as np
array=np.array([[21,43,6],[12,45,452]])
x=np.sort(array)
print(x)

[[  6  21  43]
 [ 12  45 452]]


## Filtering Arrays:
- Getting some elements out of an existing array and creating a new array out of them is called filtering.

- In NumPy, you filter an array using a boolean index list.

- If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

#### Example:

In [65]:
import numpy as np
array_1=np.array([1,2,3,4,5,6,7,8,9])
u=[True,False,True,False,True,False,True,False,True]
array= array_1[u]
print (array)

[1 3 5 7 9]
